<?php

namespace Recruiter\CommonBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UploadTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UploadTypeRepository extends EntityRepository
{
}
