parameters:
#    recruiter_common.example.class: Recruiter\CommonBundle\Example

services:
#    recruiter_common.example:
#        class: %recruiter_common.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]